version: '3.8'

services:
  front:
    container_name: sacco-front
    build: ./front
    ports:
      - "${FRONT_PORT}:3000"
      - "24678:24678"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      port: ${FRONT_PORT}
    depends_on:
      - api
  
  api:
    container_name: sacco-api
    build:
      context: './api'
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      # NODE_ENV: ${NODE_ENV}
      # MONGO_URI: ${MONGO_URL}/sacco_db  # MongoDB URI
      PORT: ${API_PORT}

  mongo:
    image: mongo:8
    container_name: sacco-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    container_name: sacco-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: sacco-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mongo: {}